-- Step 1: Explore your data
-- Explore all objecs in the database
select * from INFORMATION_SCHEMA.TABLES

-- Explore all the column in the database
select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='dim_customers'

-- Step 2 : Dimension Exploration
-- Identifying the unique value in each dimention (Distinct)
-- recogniz how data might be grouped or segmented 

Select distinct country from Gold.dim_customers
Select distinct category from Gold.dim_product
Select distinct category,subcategory from Gold.dim_product
Select distinct category,subcategory,product_name from Gold.dim_product order by 1,2,3

-- Step 3 : Date Exploration
-- identify the earliest and latest dates
-- identify the timespan (min/max)
select min(birthdate) as min,max(birthdate) as max from Gold.dim_customers
select min(create_date) as min,max(create_date) as max from Gold.dim_customers

select min(start_date) as min,max(start_date) as max from Gold.dim_product

select min(order_date) as min,max(order_date) as max from Gold.fact_sales
select min(shipping_date) as min,max(shipping_date) as max from Gold.fact_sales
select min(due_date) as min,max(due_date) as max from Gold.fact_sales

-- Step 4 : Measure Exploration
-- sum , avg values of measurable quantity
select * from Gold.dim_customers
select * from Gold.fact_sales
-- Find the total sales
select SUM(sales_amount) as Total_sales from Gold.fact_sales
-- find how many items are sold
select SUM(quantity) as Total_item_sold from Gold.fact_sales
-- find the avg selling price
select avg(price) as Avg_price from Gold.fact_sales
-- find the total number of orders
select COUNT(order_number) as Number_of_order from Gold.fact_sales
select COUNT(Distinct order_number) as Number_of_order from Gold.fact_sales
-- find the total number of products
select count(product_id) as Total_product from Gold.dim_product
-- find the total number of customers
select count(customer_id) as Total_customer from Gold.dim_customers
-- find the total number of customers that have placed the order
select count(distinct customer_key) as Total_customer from Gold.fact_sales
-- Generate a report
select 'Total_sales' as measure_name, SUM(sales_amount) as measure_value from Gold.fact_sales
Union All
select 'Total_item_sold' as measure_name, SUM(quantity) as measure_value from Gold.fact_sales
Union All
select 'Avg_price' as measure_name, avg(price) as measure_value from Gold.fact_sales
Union All
select 'Number_of_order' as measure_name, COUNT(Distinct order_number) as measure_value from Gold.fact_sales
Union All
select 'Total_product' as measure_name, count(product_id) as measure_value from Gold.dim_product
Union All
select 'Total_customer' as measure_name, count(customer_id) as measure_value from Gold.dim_customers
Union All
select 'NO_Customer_Placed_order' as measure_name, count(distinct customer_key) as measure_value from Gold.fact_sales

-- Step 5 : Magnitude Analysis
-- compare measure value across different category
select * from Gold.fact_sales

-- find total customer by country
select country,count( customer_key) as Number_of_customer from Gold.dim_customers group by country order by country
select country,count( distinct customer_key) as Number_of_customer from Gold.dim_customers group by country order by country
-- find total customer by gender
select gender,count( customer_key) as Number_of_customer from Gold.dim_customers group by gender order by gender
select gender,count( distinct customer_key) as Number_of_customer from Gold.dim_customers group by gender order by gender
-- find total product by category
select category,count( product_key) as Number_of_customer from Gold.dim_product group by category order by category
select category,count( distinct product_key) as Number_of_customer from Gold.dim_product group by category order by category
-- what is the avg cost in each category
select category,Avg( cost) as Avg_cost from Gold.dim_product group by category order by category
select category,Avg( distinct cost) as Avg_cost from Gold.dim_product group by category order by category
-- What is the total revenue generated in each category
select p.category,sum(s.sales_amount) as Total_sales from Gold.fact_sales s
left Join Gold.dim_product p on p.product_key=s.product_key group by p.category
-- find the total revenue generated by each customer
select  c.customer_key,c.first_name,c.last_name,sum(s.sales_amount) as Total_sales from Gold.fact_sales s
left Join Gold.dim_customers c on c.customer_key=s.customer_key group by c.customer_key,c.first_name,c.last_name
-- what is the distribution of sold items across country
select  c.country,sum(s.quantity) as Total_quantity from Gold.fact_sales s
left Join Gold.dim_customers c on c.customer_key=s.customer_key group by c.country
 
 -- Step 6 : Ranking
 select * from Gold.fact_sales
 -- which 5 product generate highest revenue
select top 5 p.product_name,sum(s.sales_amount) as Total_sales from Gold.fact_sales s
left Join Gold.dim_product p on p.product_key=s.product_key group by p.product_name order by p.product_name desc 

select p.product_name,sum(s.sales_amount) as Total_sales, ROW_NUMBER() over (order by sum(s.sales_amount) DESC) as Rank from Gold.fact_sales s
left Join Gold.dim_product p on p.product_key=s.product_key group by p.product_name 

 -- what are the 5 worst performing products in terms of sales
select top 5 p.product_name,sum(s.sales_amount) as Total_sales from Gold.fact_sales s
left Join Gold.dim_product p on p.product_key=s.product_key group by p.product_name order by p.product_name Asc 
